const skillList = [
  "C++",
  "SQL",
  "Python",
  "Java",
  "HTML",
  "Ladder",
  "JavaScript",
  "Servers",
  "Network Security",
  "Big Data",
  "Algorithms",
  "SPARK",
  "SAS",
  "Artificial Intelligence",
  "Ruby",
  "Analytical Skills",
  "Data Analytics",
  "Data Mining",
  "Database Design",
  "Database Management",
  "Debugging",
  "Design",
  "Development",
  "Network Architecture",
  "Operating Systems",
  "Software Development and Programming",
  "Cloud Computing",
  "Cybersecurity",
  "Project Management",
  "Graphic Design",
  "UX/ UI Design",
  "Communication",
  "Collaboration",
  "Problem-Solving",
  "Critical Thinking",
  "Adaptability",
  "Leadership",
  "Organization",
  "Negotiation",
  "Innovation",
  "Interpersonal Skills",
  "Presentation",
  "Swift",
  "Go",
  "PHP",
  "React",
  "Angular",
  "Vue.js",
  "Node.js",
  "Statistical Analysis",
  "R",
  "Excel",
  "Tableau",
  "Power BI",
  "MATLAB",
  "Machine Learning Algorithms",
  "Deep Learning Architecture",
  "Natural Language Processing (NLP)",
  "OpenCV",
  "TensorFlow",
  "PyTorch",
  "OpenAI Gym",
  "Stable Baselines",
  "RLlib",
  "Network protocols",
  "Firewalls",
  "Intrusion detection systems (IDS) and Intrusion prevention systems (IPS)",
  "Virtual private networks (VPNs)",
  "Vulnerability Assessment",
  "Penetration Testing",
  "Incident Response",
  "Digital Forensics",
  "Project Planning and Scheduling",
  "Project Budgeting",
  "Cost Management",
  "Risk Management",
  "Project Documentation",
  "Project charters",
  "Stakeholder communication plans",
  "Change Management",
  "Search Engine Optimization (SEO)",
  "Search Engine Marketing (SEM)",
  "Google Ads",
  "Social Media Marketing",
  "Content Marketing",
  "Blog writing",
  "A/B Testing",
  "Marketing Automation",
  "Conversion Rate Optimization (CRO)",
  "User Experience (UX) Optimization",
  "Influencer Marketing",
  "Adobe Creative Suite (Adobe Photoshop, Illustrator, InDesign, etc.)",
  "Typography",
  "Layout Design",
  "Color Theory",
  "Visual brand identities",
  "Illustration",
  "Custom graphics",
  "Image Editing and Retouching",
  "Print Design",
  "User Interface (UI) Design",
  "Web Design",
  "Project Closure and Evaluation",
  "User Interviews",
  "Surveys and Questionnaires",
  "Usability Testing",
  "Information Design",
  "Wireframing",
  "Interaction Design",
  "Prototyping",
  "Adobe XD",
  "Sketch",
  "Figma",
  "InVision",
  "Typography and Layout",
  "Heatmaps",
  "Microsoft Clarity",
  "Hotjar",
  "Crazy Egg",
  "Data Analysis",
  "Google Analytics",
  "Mixpanel",
  "Responsive Design",
  "Accessibility Design",
  "Teamwork",
  "Respect",
  "Trust building",
  "Accountability",
  "Mediation",
  "Relationship building",
  "Diplomacy",
  "Active engagement",
  "Delegation",
  "Analytical skills",
  "Data assessment",
  "Evaluation",
  "Creativity",
  "Open-minded",
  "Persistence",
  "Agility",
  "Identifying patterns",
  "Reasoning",
  "Logical and rational thinking processes",
  "Data-based decision-making",
  "Critical reading",
  "Evidence-based reasoning",
  "Systematic thinking",
  "Resilience",
  "Proactivity",
  "Problem-solving",
  "Learning agility",
  "Self-motivation",
  "Versatility",
  "Accommodating change",
  "Initiative",
  "Self-confidence",
  "Decision-making",
  "Inspiration",
  "Navigating challenges and change",
  "Understanding different perspectives",
  "Empathy",
  "Compassion",
  "Vision",
  "Taking responsibility",
  "Coaching",
  "Mentoring",
  "Providing feedback",
  "Conflict resolution",
  "Promoting teamwork",
  "Honesty",
  "Transparency",
  "Work ethics",
  "Influence",
  "Empowerment",
  "Personal and professional development",
  "Time management",
  "Strategizing",
  "Prioritization",
  "Attention to detail",
  "Multitasking",
  "Task delegation",
  "Workflow optimization",
  "Documentation",
  "Record-keeping",
  "Goal setting",
  "Critical analysis",
  "Mutual understanding",
  "Flexibility",
  "Sharing responsibilities",
  "Valuing contributions",
  "Assertiveness",
  "Networking",
  "Reliability",
  "Integrity",
  "CSS"
];

export default skillList;
